remote_theme: chrisrhymes/bulma-clean-theme
title: "Speedy Shortcuts"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "personal description"
show_sidebar: false
menubar: menu